#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell available, it is
#       recommended to use that to run this script.
#
#   (2) The Java Virtual Machine must be installed on the system. Make sure that
#       JAVA_HOME is set so it can find the Java executable.
#
##############################################################################

# Attempt to set APP_HOME
# Resolve links: $0 may be a symlink
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}
    case $link in
    /*) app_path=$link ;;
    *) app_path=$APP_HOME$link ;;
    esac
done

# This is normally unused
app_base_name=${0##*/}
APP_HOME=$( cd "${app_path%"${app_path##*/}"}" && pwd -P ) || exit

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn() {
    if [ "$VERBOSE" = yes ]; then
        printf '%s\n' "$*"
    fi
}

die() {
    printf '%s\n' "$1" >&2
    exit "$2"
}

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$( uname )" in
*CYGWIN*) cygwin=true ;;
*Darwin*) darwin=true ;;
*MSYS* | *MINGW*) msys=true ;;
*NONSTOP*) nonstop=true ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Determine the Java command to use to start the jvm.
if [ -n "$JAVA_HOME" ]; then
    if [ -x "$JAVA_HOME/jre/sh/java" ]; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ]; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the location of
your Java installation."
    fi
else
    JAVACMD=java
    if ! command -v java >/dev/null 2>&1; then
        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the location of
your Java installation."
    fi
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$msys" && ! "$nonstop"; then
    case $OSTYPE in
    darwin*)
        darwin=true
        ;;
    esac
fi

if [ "$darwin" = true ] && ! jopt_skip_mac_opts; then
    DEFAULT_JVM_OPTS="$DEFAULT_JVM_OPTS '-XX:+UseGCLogFileRotation' '-XX:NumberOfGCLogFiles=3' '-XX:GCLogFileSize=100m' '-Xloggc:$APP_HOME/build/gc.log'"
fi

if [ "$cygwin" = true ] || [ "$msys" = true ]; then
    APP_HOME=$( cygwin_path "$APP_HOME" )
    CP=$( cygwin_path "$CLASSPATH" )
    sed -i 's/^/\//' <<<"$CP"
    CLASSPATH=$( cygwin_path "$CLASSPATH" )
fi

# Now convert the arguments - kludge to limit ourselves to /bin/sh
for arg; do
    if
        case $arg in
        -*)
            false
            ;;
        *)
            true
            ;;
        esac
    then
        arg=$( printf '%s\n' "$arg" | sed "s/'/'\\\\''/g" )
        printf '%s\n' "'$arg'" >>current_args.txt
    else
        printf '%s\n' "'$arg'" >>current_args.txt
    fi
done
split_args=$( cat current_args.txt | xargs )
rm -f current_args.txt
exec "$JAVACMD" "${DEFAULT_JVM_OPTS[@]}" -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "${split_args[@]}"
